apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-result-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30012
  selector:
     name: result-app-pod
     app: demo-voting-app
